
spring:
  application:
    name: dsmhackertone

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}

    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
      format_sql: true
